<ul class="nav nav-pills nav-stacked">
    <li <?php if($path == 'event') echo 'class="active"'; ?>><a href="events">Events</a></li>   
    <li <?php if($path == 'competition') echo 'class="active"'; ?>><a href="competitions">Competitions</a></li>
    <li <?php if($path == 'workshop') echo 'class="active"'; ?>><a href="workshops">Workshops</a></li>
    <li <?php if($path == 'proshow') echo 'class="active"'; ?>><a href="proshows">Professional Shows </a></li> 
    <li <?php if($path == 'schedule') echo 'class="active"'; ?>><a href="schedules">Schedule</a></li>
</ul>