<!-- Add FBLike. Google+1 and Twitter Follow button or Tweet intent -->

<html>
    <head>
      <title>Antaragini Portal</title>
    </head>
    <body>      
       <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Flocalhost&amp;send=false&amp;layout=standard&amp;width=200&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=80&amp;appId=362887313735570" scrolling="no" frameborder="0" 
					style="border:none; overflow:hidden; width:200px; height:80px;" allowTransparency="true">
	   </iframe>
    </body>
 </html>

<div class='g-plusone' data-annotation='inline' data-width='100'></div>

<script type='text/javascript'>
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script> <br /> <br />

<a href='https://twitter.com/antaragni' class='twitter-follow-button' data-show-count='false' data-size='large'>Follow @twitter</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='//platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','twitter-wjs');</script>

